// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnbdwKP95RKL_0UyJmBvB_37DQLsiMFps',
    appId: '1:429490705566:web:fe73b64a65377344ac978f',
    messagingSenderId: '429490705566',
    projectId: 'learningmanagement-a873e',
    authDomain: 'learningmanagement-a873e.firebaseapp.com',
    storageBucket: 'learningmanagement-a873e.firebasestorage.app',
    measurementId: 'G-149RFGYV3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbdwKP95RKL_0UyJmBvB_37DQLsiMFps',
    appId: '1:429490705566:android:fe73b64a65377344ac978f',
    messagingSenderId: '429490705566',
    projectId: 'learningmanagement-a873e',
    storageBucket: 'learningmanagement-a873e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnbdwKP95RKL_0UyJmBvB_37DQLsiMFps',
    appId: '1:429490705566:ios:fe73b64a65377344ac978f',
    messagingSenderId: '429490705566',
    projectId: 'learningmanagement-a873e',
    storageBucket: 'learningmanagement-a873e.firebasestorage.app',
    iosBundleId: 'com.example.learningmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnbdwKP95RKL_0UyJmBvB_37DQLsiMFps',
    appId: '1:429490705566:macos:fe73b64a65377344ac978f',
    messagingSenderId: '429490705566',
    projectId: 'learningmanagement-a873e',
    storageBucket: 'learningmanagement-a873e.firebasestorage.app',
    iosBundleId: 'com.example.learningmanagement',
  );
}